export { default as Home } from './Home'
export { default as Add } from './Add'
export { default as Search } from './Search'
export { default as Like } from './Like'
export { default as Profile } from './Profile'
export { default as Login } from './Login'
export { default as Register } from './Register'